name: Test
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  SSH:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: Run scripts in server
      uses: appleboy/ssh-action@master
      with:
          key: ${{ secrets.PRIVATE_EC2_KEY }}
          host: ${{ secrets.PRIVATE_EC2_IP }}
          username: ubuntu
          script: |
            ls
