name: Test
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  connect:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: |
       echo "${{secrets.PRIVATE_EC2_PEM}}" >> ${{secrets.PRIVATE_EC2_PEM}}
       cat ${{secrets.PRIVATE_EC2_PEM}}
       chmod 400 ${{secrets.PRIVATE_EC2_PEM}}
       ssh -i ${{secrets.PRIVATE_EC2_PEM}} ubuntu@54.180.24.185
